### ISSUE TITLE
Add new `date_range` data to objects

### ISSUE THREAD

**Issue by geealbers** [thegetty/ancient-glass#187]
To facilitate sorting by date on main catalogue objects grid page, we need to add explicit date ranges to the object data. Each range is going to be one or more strings, each of which is a 100-year span. To ensure that these are ordered correctly in the dropdown filter, each string is preceded by a two-digit number a colon and a space, which is later stripped away with some javascript on the backend.

Here's are some examples:

```yaml
-
    id: cat-1
    label: "Cat. 1"
    accession_number: "2003.146"
    link: <https://www.getty.edu/art/collection/objects/221513>
    dimensions: "est. H. 12.6, pres. H. 9.5, Diam. rim 2.5, Diam. base 2.8 cm; Wt. 83.46 g"
    date: "New Kingdom, Eighteenth Dynasty; Tuthmosis IV to Amenhotep IV/Akhenaten before Amarna period; 1401–1347 BCE"
    start_date: "-1401"
    end_date: "-1347"
    date_range: [ "02: 1400–1300 BCE" ]
-
    id: cat-2
    label: "Cat. 2"
    accession_number: "2004.3"
    link: <https://www.getty.edu/art/collection/objects/221454>
    dimensions: "H. 8.5, Diam. rim 2.3, max. Diam. 4.2 cm; Wt. 52.20 g"
    date: "New Kingdom; 1540–1075 BCE"
    start_date: "-1540"
    end_date: "-1075"
    date_range: [ "01: 1500–1400 BCE", "02: 1400–1300 BCE", "03: 1300–1200 BCE", "04: 1200–1100 BCE", "05: 1100–1000 BCE" ]
```

When adding date ranges, you can go by the `start_date` and `end_date` values, however, please just give a glance at the `date` value to make sure they all still align. The `date` is always correct, but I'm not sure the `start_date` and `end_date` values were always updated when changes to `date` were made during editing.

The full list of numbered ranges you will use is:

```
01: 1500–1400 BCE
02: 1400–1300 BCE
03: 1300–1200 BCE
04: 1200–1100 BCE
05: 1100–1000 BCE
06: 1000–900 BCE
07: 900–800 BCE
08: 800–700 BCE
09: 700–600 BCE
10: 600–500 BCE
11: 500–400 BCE
12: 400–300 BCE
13: 300–200 BCE
14: 200–100 BCE
15: 100–0 BCE
16: 0–100 CE
17: 100–200 CE
18: 200–300 CE
19: 300–400 CE
20: 400–500 CE
21: 500–600 CE
22: 600–700 CE
23: 700–800 CE
24: 800–900 CE
25: 900–1000 CE
26: 1000–1100 CE
27: 1100–1200 CE
28: 1200–present
```
