### ISSUE TITLE
Add ability to customize tombstone labels

### ISSUE THREAD

**Issue by geealbers** [thegetty/ancient-glass#2]
The tombstone uses `modeling_technique_and_decoration`, which Quire processes into "Modeling Technique And Decoration", but the "And" should be lower case. We'll need to implement a similar system for `object_display_order` that we have on `object_filters` that let's the user specify the label text.

```yaml
object_display_order:
  - accession_number
  - dimensions
  - date
  - attribution
  - material
  - field: modeling_technique_and_decoration
    label: "Modeling Technique and Decoration"
```
